config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'static_pages/about'
  get 'static_pages/contact'

  resources :posts do
    resources :comments
  end

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comments, dependent: :destroy
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name_author, :comment_body))
    redirect_to post_path(@post)
end

  def destroy; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: %i[show update edit destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was deleted.' }
      format.json { head :no_content }
    end
    end

  private

  def post_params
    params.require(:post).permit(:title, :content, :picture)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def about; end

  def contact; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name_author %>:</strong>
          <%= comment.comment_body %>
        </p>
      </div>
    </div>
    <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :name_author, input_html: { class: 'input' }, wrapper: false, label: 'Name', label_html: { class: 'label' } %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.input :comment_body, input_html: { class: 'textarea' }, wrapper: false, label: 'Comment', label_html: { class: 'label' } %>
  </div>
</div>
<%= f.button :submit, class: "button is-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabyBlogger</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="hero is-primary is-small-with-navbar">
      <div class="hero-head">
        <nav class="navbar">
          <div class="logo">
            <strong><%= link_to 'BabyBlogger', root_path, class: "navbar-item", id: "baby_blogger-nav_item" %>
            </strong>
          </div>
          <div class="navbar-brand">
            <a role="button" class="navbar-burger burger" id="nav-toggle" aria-label="menu" aria-expanded="false" data-target="navbarMenuHeroA" onclick="toggleBurger()">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
              <div class="navbar-item">
                <%= link_to "Create New Post", new_post_path %>
              </div>
              <div class="navbar-item">
                <%= link_to "About", static_pages_about_path%>
              </div>
              <div class="navbar-item">
                <%= link_to "Contact", static_pages_contact_path %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </div>
    <section class="section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>

<div class="field">
  <div class="control">
    <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>
<div class="field">
  <div class="control" id="control-textarea">
    <%= f.input :content, as: :trix_editor, input_html: { class: 'textarea' }, placeholder: "write here", wrapper: false, label: "Post", label_html: { class: 'label' } %>
  </div>
</div>
<div class="field">
  <div class="control">
    <label for="file-field">Upload Image</label>
    <%= f.file_field :picture, id:"file-field", accept: 'image/png,image/jpeg,image/jpg' %>
  </div>
</div>

<%= f.button :submit, class: "button is-primary" %>

<% end %>

app/views/posts/edit.html.erb
<% content_for :page_title, 'Edit Post' %>

  <div class="container">
    <%= render 'form' %>
  </div>

app/views/posts/index.html.erb
<% content_for :page_title, 'Blog Posts' %>

  <div class="container">
    <div class="columns is-multiline">
      <% @posts.each do |post| %>
        <div class="column column-post is-flex is-one-quarter">
          <div class="box">
            <h2 class="title is-4">
              <%= link_to post.title, post %>
            </h2>
            <%= sanitize(post.content.truncate(100)) %>
            <hr/>
            <%= link_to 'Read more', post %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/posts/new.html.erb
<% content_for :page_title, 'Create a New Post' %>

  <div class="container">
    <%= render 'form' %>
  </div>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

  <div class="container">
    <div class="box">
      <%= sanitize @post.content %>
    </div>
    <%= image_tag(@post.picture_url, width: 600) if @post.picture.present? %>

    <nav class="level is-mobile">
      <!-- Left side -->
      <div class="level-left"></div>
      <!-- Right side -->
      <div class="level-right">
        <p class="level-item">
          <%= link_to "Edit", edit_post_path(@post), class:"button" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
        </p>
      </div>
    </nav>
    <br/>
    <br/>
  </div>

  <div class="container">
    <h2 class="subtitle is-5">
      <strong><%= @post.comments.count %>
      </strong>
      Comments
    </h2>
    <br/>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr/>
      <h3 class="subtitle is-4">
        Please leave your comment</h3>
      <%= render 'comments/form' %>
    </div>
  </div>

app/views/static_pages/about.html.erb
<% content_for :page_title, "Hi there!" %>
  <div class="container">
    <div class="wrapper">
      <header class="header title is-3"></header>
      <article class="main is-centered">
        <p>I am Sarah Rehan - an enterprising Web Developer</p>
      </article>
      <aside class="aside aside-2">
        <nav class="panel">
          <p class="panel-heading">Top Traits</p>
          <p class="panel-block">Learner</p>
          <p class="panel-block">Achiever</p>
          <p class="panel-block">Self-motivated</p>
          <p class="panel-block">Go getter</p>
          <p class="panel-block">Dependable</p>
        </nav>
      </aside>
      <aside class="aside aside-1">
        <nav class="panel">
          <p class="panel-heading">Tech Stack</p>
          <p class="panel-block">Rails</p>
          <p class="panel-block">React</p>
          <p class="panel-block">Asp.net</p>
          <p class="panel-block">C#</p>
          <p class="panel-block">SQL</p>
        </nav>
      </aside>
      <br/>

    </div>

    <footer class="footer">
      <small class="is-pulled-right">SarahRehan 2020</small>
    </footer>
  </div>

app/views/static_pages/contact.html.erb
<% content_for :page_title, "Contact" %>

  <div class="container">
    <h2 class="title is-4 has-text-centered">Get in touch for work and feedback!</h2>
    <br>
    <div class="columns has-text-centered">
      <div class="column is-6">
        Drop an email at:
      </div>
      <div class="column is-6 ">
        sarahahmad17@gmail.com
      </div>
    </div>
    <hr/>
    <div class="columns has-text-centered">
      <div class="column is-6">
        Reach out on LinkedIn:
      </div>
      <div class="column is-6">
        ca.linkedin.com/in/sarahrehan85
      </div>
    </div>
    <hr/>

    <footer class="footer">
      <!-- <ul class="flex-container"> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> </ul> -->
      <br/>
      <small class="is-pulled-right">SarahRehan 2020</small>
    </footer>
  </div>